name: Node.js Push Pipeline

on:
  push:
    branches:
      - "**" # Runs on all branches except main

  pull_request:
    branches:
      - "*" 

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  BuildAndUnitTestApp:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v3

     
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 18

     
      - name: Install Dependencies
        run: npm install  # Installs dependencies

      - name: Build Project
        run: npm run build 

      - name: Fix Jest Permission
        run: chmod +x ./node_modules/.bin/jest

      - name: Run Unit Tests with JSON Output
        run: |
          # Run tests and generate JSON output, even if some fail
          npx jest --json --outputFile=jest-output.json --runInBand
        continue-on-error: true
      
      - name: Check Test Failures
        run: |
          # Check if the output file exists
          if [ ! -f "jest-output.json" ]; then
            echo "jest-output.json not found. Skipping checks."
            exit 0
          fi
      
          # Count major test failures
          major_failures=$(jq '[.testResults[].assertionResults[] | select(.status == "failed" and (.title | test("^major:")))] | length' jest-output.json)
      
          # Count minor test failures
          minor_failures=$(jq '[.testResults[].assertionResults[] | select(.status == "failed" and (.title | test("^minor:")))] | length' jest-output.json)
      
          echo "❗ Major test failures: $major_failures"
          echo "Minor test failures: $minor_failures"
      
          if [ "$major_failures" -gt 0 ]; then
            echo "Build failed due to major test case failures."
            exit 1
          else
            echo "No major test failures. Proceeding."
          fi
      
          if [ "$minor_failures" -gt 0 ]; then
            echo "⚠️ Minor test cases failed. Logged for reference, not blocking the build."
          fi
      

      - name: Run Unit Tests with Coverage
        run: npm test -- --runInBand --coverage

      - name: Upload Coverage Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: coverage/lcov-report/
      
      - name: Upload lcov.info
        uses: actions/upload-artifact@v4
        with:
          name: lcov
          path: coverage/lcov.info

      - name: Upload JUnit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jest-junit-report
          path: reports/junit/js-test-results.xml
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
         SONAR_TOKEN: ${{  secrets.SONAR_TOKEN  }}
         