name: Node.js Push Pipeline

on:
  push:
    branches:
      - "**" # Runs on all branches except main

  pull_request:
    branches:
      - "*" 

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  BuildAndUnitTestApp:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v3

     
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 18

     
      - name: Install Dependencies
        run: npm install  # Installs dependencies

      - name: Build Project
        run: npm run build 

      - name: Fix Jest Permission
        run: chmod +x ./node_modules/.bin/jest

      - name: Run Unit Tests
        run: ./node_modules/.bin/jest --runInBand


      - name: Check Major Test Failures
        run: |
          # Use jq to filter out major tests from the results
          major_failures=$(jq '[.testResults[] | select(.name | test("^major")) | .status] | unique' jest-output.json)
          major_failures_count=$(echo $major_failures | jq length)
          
          # If there are any major test failures, fail the build
          if [ "$major_failures_count" -gt 0 ]; then
            echo "Major test cases failed!"
            exit 1
          else
            echo "No major test cases failed. Proceeding..."
          fi

      - name: Run Unit Tests with Coverage
        run: npm test -- --runInBand --coverage

      - name: Upload Coverage Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: coverage/lcov-report/
      
      - name: Upload lcov.info
        uses: actions/upload-artifact@v4
        with:
          name: lcov
          path: coverage/lcov.info

      - name: Upload JUnit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jest-junit-report
          path: reports/junit/js-test-results.xml
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
         SONAR_TOKEN: ${{  secrets.SONAR_TOKEN  }}
         