name: Use Reusable Node.js Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "*"

jobs:
  call-nodejs-pipeline:
    uses: Rite-Technologies-23/Resuable.pushpipe.nodejs/.github/workflows/nodejs-push-pipeline.yml@main
    with:
      node-version: "18"
      run-tests: 'true'
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
